services:
  - type: web
    name: moto-weather-bot
    runtime: python
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
